# Generated by Django 4.2.13 on 2026-03-11 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('developer', models.CharField(max_length=150, verbose_name='Desarrollador / Estudio')),
                ('review', models.TextField(help_text='Escribe tu opinión, experiencia o descripción del juego.', verbose_name='Reseña personal')),
                ('year', models.PositiveIntegerField(verbose_name='Año de lanzamiento')),
                ('genre', models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('rpg', 'RPG'), ('estrategia', 'Estrategia'), ('deportes', 'Deportes'), ('carreras', 'Carreras'), ('terror', 'Terror / Survival'), ('plataformas', 'Plataformas'), ('shooter', 'Shooter'), ('simulacion', 'Simulación'), ('puzzle', 'Puzzle'), ('lucha', 'Lucha'), ('indie', 'Indie'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Género')),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps5', 'PlayStation 5'), ('ps4', 'PlayStation 4'), ('xbox_series', 'Xbox Series X/S'), ('xbox_one', 'Xbox One'), ('switch', 'Nintendo Switch'), ('mobile', 'Móvil'), ('retro', 'Retro / Otra')], default='pc', max_length=20, verbose_name='Plataforma')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado'), ('platinado', 'Platinado / 100%')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('rating', models.IntegerField(choices=[(1, '★ Pésimo'), (2, '★★ Malo'), (3, '★★★ Regular'), (4, '★★★★ Bueno'), (5, '★★★★★ Obra maestra')], default=3, verbose_name='Puntuación')),
                ('hours_played', models.PositiveIntegerField(default=0, verbose_name='Horas jugadas')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Portada')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
                'ordering': ['-created_at'],
            },
        ),
    ]
